In [ ]:
import pandas as pd
import os

In [ ]:
os.chdir('..')
df = pd.read_csv('src/best_class_metrics.csv')
df_oversampler = pd.read_csv('src/class_metrics_random_oversampler.csv')
df_undersampler = pd.read_csv('src/class_metrics_random_undersampler.csv')
df_smote = pd.read_csv('src/class_metrics_smote.csv')
df_dict_log = pd.read_csv('src/class_metrics_dict_log.csv')
df_dict_sqrt = pd.read_csv('src/class_metrics_dict_sqrt.csv')

In [3]:
result = df_oversampler - df
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0  0.000799   0.008556  0.000799  0.004735  0.000524
1      0      0 -0.001191   0.009109 -0.001191  0.004002  0.001709
2      0      0 -0.001755   0.036177 -0.001755  0.032255  0.001932
3      0      0  0.003457   0.016134  0.003457  0.013690  0.000809
4      0      0  0.005178   0.019423  0.005178  0.023400  0.002634
5      0      0  0.054014  -0.003561  0.054014  0.040836  0.011573

In [11]:
result = df_undersampler - df
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0 -0.024776  -0.046361 -0.024776 -0.035919 -0.012329
1      0      0 -0.019775  -0.025994 -0.019775 -0.022941 -0.018623
2      0      0 -0.046811  -0.030938 -0.046811 -0.038341 -0.012489
3      0      0 -0.018765   0.005322 -0.018765 -0.001011 -0.002465
4      0      0 -0.046598  -0.018527 -0.046598 -0.026973 -0.009725
5      0      0 -0.046543  -0.043489 -0.046543 -0.049485 -0.034093

In [4]:
result = df_smote - df
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0 -0.000320   0.011818 -0.000320  0.005826  0.000894
1      0      0 -0.000306   0.008069 -0.000306  0.003921  0.002096
2      0      0  0.007022   0.035439  0.007022  0.033612  0.003442
3      0      0  0.001481   0.021645  0.001481  0.017410  0.001133
4      0      0  0.005178   0.033514  0.005178  0.039484  0.002708
5      0      0  0.063145  -0.003662  0.063145  0.047537  0.013785

In [5]:
result = df_dict_log - df
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0 -0.015825   0.017311 -0.015825  0.000762  0.001999
1      0      0  0.010959  -0.002827  0.010959  0.003919  0.005929
2      0      0 -0.263897   0.205295 -0.263897  0.042946  0.003325
3      0      0 -0.084938   0.121188 -0.084938  0.055922  0.000751
4      0      0 -0.378698   0.412730 -0.378698  0.154058  0.003723
5      0      0  0.276770  -0.047643  0.276770  0.161941  0.054044

In [6]:
result = df_dict_sqrt - df
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0 -0.009431   0.014950 -0.009431  0.002831  0.001860
1      0      0  0.010721  -0.001684  0.010721  0.004391  0.005401
2      0      0 -0.129901   0.145683 -0.129901  0.074509  0.003151
3      0      0 -0.035062   0.071234 -0.035062  0.042217  0.000825
4      0      0 -0.204142   0.225490 -0.204142  0.158365  0.003971
5      0      0  0.212439  -0.018749  0.212439  0.139656  0.048742

In [7]:
result = df_smote - df_oversampler
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0 -0.001119   0.003263 -0.001119  0.001090  0.000371
1      0      0  0.000885  -0.001040  0.000885 -0.000081  0.000386
2      0      0  0.008777  -0.000738  0.008777  0.001356  0.001510
3      0      0 -0.001975   0.005512 -0.001975  0.003720  0.000325
4      0      0  0.000000   0.014091  0.000000  0.016084  0.000073
5      0      0  0.009131  -0.000101  0.009131  0.006701  0.002212

In [8]:
result = df_smote - df_dict_log
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0  0.015505  -0.005493  0.015505  0.005064 -0.001105
1      0      0 -0.011266   0.010896 -0.011266  0.000002 -0.003834
2      0      0  0.270919  -0.169855  0.270919 -0.009334  0.000117
3      0      0  0.086420  -0.099542  0.086420 -0.038512  0.000382
4      0      0  0.383876  -0.379216  0.383876 -0.114574 -0.001016
5      0      0 -0.213625   0.043981 -0.213625 -0.114404 -0.040258

In [9]:
result = df_smote - df_dict_sqrt
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0  0.009111  -0.003131  0.009111  0.002995 -0.000966
1      0      0 -0.011028   0.009753 -0.011028 -0.000470 -0.003306
2      0      0  0.136922  -0.110244  0.136922 -0.040898  0.000290
3      0      0  0.036543  -0.049588  0.036543 -0.024807  0.000309
4      0      0  0.209320  -0.191976  0.209320 -0.118880 -0.001263
5      0      0 -0.149294   0.015087 -0.149294 -0.092119 -0.034957

In [10]:
result = df_dict_log - df_dict_sqrt
result.head(6)

   class  count  accuracy  precision    recall        f1   roc_auc
0      0      0 -0.006394   0.002361 -0.006394 -0.002069  0.000139
1      0      0  0.000238  -0.001143  0.000238 -0.000472  0.000528
2      0      0 -0.133996   0.059611 -0.133996 -0.031563  0.000174
3      0      0 -0.049877   0.049954 -0.049877  0.013705 -0.000073
4      0      0 -0.174556   0.187240 -0.174556 -0.004307 -0.000248
5      0      0  0.064331  -0.028895  0.064331  0.022285  0.005301