In [ ]:
import pandas as pd
import os

In [ ]:
os.chdir('..')
df = pd.read_csv('src/clear_data.csv')
df.head()

,ndvi_21.09,ndvi_6.10.,ndvi_29.04,ndvi_6.08.,ndvi_9.10.,ndvi_18.05,ndvi_16.07,ndvi_18.09,ndvi_01.10,ndvi_13.07,...,ndmi_04.08,ndmi_06.08,ndmi_6.10.,ndmi_08.05,ndmi_09.10,ndmi_13.07,ndmi_16.07,ndmi_18.05,ndmi_18.09,id_2
0,0.10750,0.10875,0.07247,0.17710,0.11786,0.23621,0.28439,0.26938,0.10349,0.25365,...,0.03752,-0.04252,-0.06373,-0.07223,-0.09070,0.01767,0.04530,0.01750,0.10671,1
1,0.05252,0.11331,0.07743,0.11654,0.09358,0.17090,0.43870,0.39618,0.05951,0.49850,...,0.24846,-0.11630,-0.06300,-0.12535,-0.11175,0.31008,0.24156,-0.07204,0.22557,1
2,0.04890,0.11143,0.07619,0.11572,0.08853,0.23884,0.43942,0.41737,0.05929,0.49731,...,0.26675,-0.12063,-0.06573,-0.12332,-0.11834,0.31579,0.24107,0.00183,0.24557,1
3,0.04335,0.10651,0.07023,0.11141,0.10000,0.25608,0.42896,0.39366,0.05790,0.49943,...,0.25693,-0.11436,-0.06438,-0.12019,-0.10554,0.31479,0.25053,0.03882,0.22925,1
4,0.04398,0.10706,0.07011,0.11159,0.09398,0.24354,0.45498,0.39746,0.05912,0.49912,...,0.25238,-0.12883,-0.06845,-0.12359,-0.12531,0.31356,0.27918,0.02449,0.23378,1

In [15]:
df['id_2'].value_counts()

id_2
2    148389
6     85182
1     31592
4     10227
3      8632
5      6829
Name: count, dtype: int64

Разделим классы на редкие и нередкие: классы 2, 6, 1 будут нередкими, а классы 4, 3, 5, собственно, редкими

In [16]:
df_B = df[~df['id_2'].isin([4, 3, 5])]
df_B.to_csv('dataset_B.csv', index=False)

In [17]:
df_C = df[~df['id_2'].isin([1, 2, 6])]
df_C.to_csv('dataset_C.csv', index=False)

In [18]:
df['rarity'] = df['id_2'].apply(lambda x: 0 if x in [2, 6, 1] else 1)
df = df.drop(columns=['id_2'])
df.to_csv('dataset_A.csv', index=False)
df.head()

,ndvi_21.09,ndvi_6.10.,ndvi_29.04,ndvi_6.08.,ndvi_9.10.,ndvi_18.05,ndvi_16.07,ndvi_18.09,ndvi_01.10,ndvi_13.07,...,ndmi_04.08,ndmi_06.08,ndmi_6.10.,ndmi_08.05,ndmi_09.10,ndmi_13.07,ndmi_16.07,ndmi_18.05,ndmi_18.09,rarity
0,0.10750,0.10875,0.07247,0.17710,0.11786,0.23621,0.28439,0.26938,0.10349,0.25365,...,0.03752,-0.04252,-0.06373,-0.07223,-0.09070,0.01767,0.04530,0.01750,0.10671,0
1,0.05252,0.11331,0.07743,0.11654,0.09358,0.17090,0.43870,0.39618,0.05951,0.49850,...,0.24846,-0.11630,-0.06300,-0.12535,-0.11175,0.31008,0.24156,-0.07204,0.22557,0
2,0.04890,0.11143,0.07619,0.11572,0.08853,0.23884,0.43942,0.41737,0.05929,0.49731,...,0.26675,-0.12063,-0.06573,-0.12332,-0.11834,0.31579,0.24107,0.00183,0.24557,0
3,0.04335,0.10651,0.07023,0.11141,0.10000,0.25608,0.42896,0.39366,0.05790,0.49943,...,0.25693,-0.11436,-0.06438,-0.12019,-0.10554,0.31479,0.25053,0.03882,0.22925,0
4,0.04398,0.10706,0.07011,0.11159,0.09398,0.24354,0.45498,0.39746,0.05912,0.49912,...,0.25238,-0.12883,-0.06845,-0.12359,-0.12531,0.31356,0.27918,0.02449,0.23378,0